FROM node:18-alpine

WORKDIR /app

# Cài openssl cho Alpine (giải quyết warning libssl)
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "npx prisma db push --accept-data-loss && npm run dev"]